baseURL = "https://amerghazal.github.io/"
languageCode = "en-us"
title = "amerghazal"
theme = "whiteplain"
copyright = "&copy; Copyright 2019 amerghazal"

[params.author]
  name = "amerghazal"
  github = "amerghazal"

[[menu.main]]
  name = "Categories"
  identifier = "categories"
  url = "/categories/"
  weight = 1

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 4
